services:
  - type: web
    name: bot-invs
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
    autoDeploy: true
    healthCheckPath: "/"