name: Kirim Laporan Harian

on:
  schedule:
    - cron: '0 0 * * *'  # Jalankan tiap hari jam 00:00 UTC = 07.00 WIB

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run bot (test)
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
      run: |
        python main.py

    - name: Deploy to Render
      uses: jakejarvis/render-action@v2
      with:
        service: bot-invs
        branch: main
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
